### ISSUE TITLE
Switching post does not update the title, data and reading time

### ISSUE THREAD

**Issue by Ak4zh** [mattjennings/sveltekit-blog-template#13]
When you switch to a different post from a post page by clicking on the `PostPreview`, the content updates but the post title, data and reading time does not get updated, it still shows the data of previous post.

**Comment by mattjennings** [comment]
Thanks for reporting this. This is because I was destructuring the `post` prop in `[slug].svelte` - which made them not reactive. Fix was to access those properties via `post.xyz` instead on the page.

See https://github.com/mattjennings/sveltekit-blog-template/commit/a73c63d3a41a5c1a7cd489eebd219ef077bce237
